config/routes.rb
Rails.application.routes.draw do
  root 'sales#new'
  resources :sales, only: [:index, :show, :new, :create]

end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: :show

  def index
    @sales = Sale.all
  end

  def new
    @sale = Sale.new
  end

  def show
  end

  def create
    @sale = Sale.new(sale_params)

    if @sale.save
      redirect_to @sale, notice: 'Sale action was successfully created.'
    else
      render :new
    end
  end

  private
    def set_sale
      @sale = Sale.find(params[:id])
    end

    def sale_params
      params.require(:sale).permit(:site)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sinta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sales</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Site</th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.id %></td>
        <td><%= sale.site %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<%= form_for(@sale) do |f| %>
  <%= f.label :site %>
  <%= f.collection_select(:site, Site.order(:url), :url, :url) %>
  <%= f.submit %>
<% end %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sale site:</strong>
  <%= @sale.site %>
</p>

<%= link_to 'to Sales list', sales_path %>